version: '3.2'

services:
  connect:
    image: connect
    build: ..
    ports:
      - "80:80"
    environment:
      COMMA_URL_ROOT: https://api.springerelectronics.com/
      ATHENA_URL_ROOT: https://api.springerelectronics.com/ws/
      BILLING_URL_ROOT: https://billing.comma.ai/
      USERADMIN_URL_ROOT: https://useradmin.springerelectronics.com/

      SENTRY_ENV: connect-development
